version: 0.2

env:
  variables:
    BUCKET: danilop-packages

phases:
  install:
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket $BUCKET --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - packaged.yaml
