version: 0.2

env:
  variables:
    BUCKET: danilop-packages

phases:
  install:
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - >
        aws cloudformation package 
        --template-file template.yml
        --output-template packaged.yml
        --s3-bucket $BUCKET

artifacts:
  type: zip
  files:
    - template-output.yml
