version: 0.2

env:
  variables:
    BUCKET: codepipeline-eu-west-1-202477100601

phases:
  install:
    commands:
      - pip install --upgrade awscli
      - pip install --upgrade aws-sam-cli
      - aws --version
      - sam --version
  build:
    commands:
      - sam build
      - sam package --s3-bucket $BUCKET --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - packaged.yaml
